# Generated by Django 2.1.7 on 2019-03-06 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps, schema_editor):
    # 현재 모든 user들에 대해서 profile을 만들어 줍니다.
    auth_user_model = settings.AUTH_USER_MODEL.split(',') # 'auth', 'User'값이 들은 튜플이됨
    User = apps.get_model(*auth_user_model) #언패킹 기능 활용
    Profile = apps.get_model('accounts', 'Profile') #언패킹 기능 활용
    # Country = apps.get_user_model('auth', 'User')
    #반드시 apps에 있는 model을 획득해줘야함. ()에는 label입력 (apps, model_class_name)
    #AUTH_USER_MODEL의 User를 지정했으므로 위와같이 입력 (settings에따라 바뀜)

    for user in User.objects.all():
        print('create profile for user #{}'.format(user.pk))
        Profile.objects.create(user=user)

def backward_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward_func, backward_func),
    ]
