# Generated by Django 2.1.7 on 2019-03-09 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [['can_view_goldpage', 'can_view_goldpage']]},
        ),
    ]
